# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\17800\Desktop\软件P3D\qt_test_20240316\untitled_ENG.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1369, 895)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("icon_GXF.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.mdiArea = QtWidgets.QMdiArea(self.centralwidget)
        self.mdiArea.setMaximumSize(QtCore.QSize(16777215, 400))
        self.mdiArea.setObjectName("mdiArea")
        self.verticalLayout.addWidget(self.mdiArea)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.lineEdit_main_in_path = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_main_in_path.setMinimumSize(QtCore.QSize(50, 0))
        self.lineEdit_main_in_path.setText("")
        self.lineEdit_main_in_path.setObjectName("lineEdit_main_in_path")
        self.horizontalLayout.addWidget(self.lineEdit_main_in_path)
        self.toolButton_main_in_path = QtWidgets.QToolButton(self.centralwidget)
        self.toolButton_main_in_path.setObjectName("toolButton_main_in_path")
        self.horizontalLayout.addWidget(self.toolButton_main_in_path)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_3.addWidget(self.label_3)
        self.lineEdit_main_out_path = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_main_out_path.setMinimumSize(QtCore.QSize(50, 0))
        self.lineEdit_main_out_path.setText("")
        self.lineEdit_main_out_path.setObjectName("lineEdit_main_out_path")
        self.horizontalLayout_3.addWidget(self.lineEdit_main_out_path)
        self.toolButton_main_out_path = QtWidgets.QToolButton(self.centralwidget)
        self.toolButton_main_out_path.setObjectName("toolButton_main_out_path")
        self.horizontalLayout_3.addWidget(self.toolButton_main_out_path)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.toolBox = QtWidgets.QToolBox(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.toolBox.setFont(font)
        self.toolBox.setLineWidth(1)
        self.toolBox.setObjectName("toolBox")
        self.page_1 = QtWidgets.QWidget()
        self.page_1.setGeometry(QtCore.QRect(0, 0, 1347, 311))
        self.page_1.setObjectName("page_1")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.page_1)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.groupBox = QtWidgets.QGroupBox(self.page_1)
        self.groupBox.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.checkBox_pre_allToCai = QtWidgets.QCheckBox(self.groupBox)
        self.checkBox_pre_allToCai.setObjectName("checkBox_pre_allToCai")
        self.horizontalLayout_2.addWidget(self.checkBox_pre_allToCai)
        self.doubleSpinBox_allToCai_density = QtWidgets.QDoubleSpinBox(self.groupBox)
        self.doubleSpinBox_allToCai_density.setDecimals(4)
        self.doubleSpinBox_allToCai_density.setMaximum(100.0)
        self.doubleSpinBox_allToCai_density.setProperty("value", 30.0)
        self.doubleSpinBox_allToCai_density.setObjectName("doubleSpinBox_allToCai_density")
        self.horizontalLayout_2.addWidget(self.doubleSpinBox_allToCai_density)
        self.line_2 = QtWidgets.QFrame(self.groupBox)
        self.line_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.horizontalLayout_2.addWidget(self.line_2)
        self.checkBox_pre_noise = QtWidgets.QCheckBox(self.groupBox)
        self.checkBox_pre_noise.setObjectName("checkBox_pre_noise")
        self.horizontalLayout_2.addWidget(self.checkBox_pre_noise)
        self.line = QtWidgets.QFrame(self.groupBox)
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.horizontalLayout_2.addWidget(self.line)
        self.checkBox_pre_downSample = QtWidgets.QCheckBox(self.groupBox)
        self.checkBox_pre_downSample.setObjectName("checkBox_pre_downSample")
        self.horizontalLayout_2.addWidget(self.checkBox_pre_downSample)
        self.doubleSpinBox_pre_downSample_density = QtWidgets.QDoubleSpinBox(self.groupBox)
        self.doubleSpinBox_pre_downSample_density.setDecimals(4)
        self.doubleSpinBox_pre_downSample_density.setProperty("value", 0.05)
        self.doubleSpinBox_pre_downSample_density.setObjectName("doubleSpinBox_pre_downSample_density")
        self.horizontalLayout_2.addWidget(self.doubleSpinBox_pre_downSample_density)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.pushButton_pre_run = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_pre_run.setStyleSheet("")
        self.pushButton_pre_run.setObjectName("pushButton_pre_run")
        self.horizontalLayout_2.addWidget(self.pushButton_pre_run)
        self.verticalLayout_4.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_5.addWidget(self.groupBox)
        self.groupBox_3 = QtWidgets.QGroupBox(self.page_1)
        self.groupBox_3.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.groupBox_3.setObjectName("groupBox_3")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBox_3)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.checkBox_seg_lettuce = QtWidgets.QCheckBox(self.groupBox_3)
        self.checkBox_seg_lettuce.setChecked(True)
        self.checkBox_seg_lettuce.setObjectName("checkBox_seg_lettuce")
        self.horizontalLayout_6.addWidget(self.checkBox_seg_lettuce)
        self.line_3 = QtWidgets.QFrame(self.groupBox_3)
        self.line_3.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.horizontalLayout_6.addWidget(self.line_3)
        self.checkBox_seg_singleLeaf = QtWidgets.QCheckBox(self.groupBox_3)
        self.checkBox_seg_singleLeaf.setObjectName("checkBox_seg_singleLeaf")
        self.horizontalLayout_6.addWidget(self.checkBox_seg_singleLeaf)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem1)
        self.pushButton_seg_run = QtWidgets.QPushButton(self.groupBox_3)
        self.pushButton_seg_run.setObjectName("pushButton_seg_run")
        self.horizontalLayout_6.addWidget(self.pushButton_seg_run)
        self.gridLayout_2.addLayout(self.horizontalLayout_6, 0, 0, 1, 1)
        self.horizontalLayout_5.addWidget(self.groupBox_3)
        self.verticalLayout_2.addLayout(self.horizontalLayout_5)
        self.groupBox_4 = QtWidgets.QGroupBox(self.page_1)
        self.groupBox_4.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.groupBox_4.setObjectName("groupBox_4")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.groupBox_4)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.checkBox_phe_lettuce = QtWidgets.QCheckBox(self.groupBox_4)
        self.checkBox_phe_lettuce.setObjectName("checkBox_phe_lettuce")
        self.horizontalLayout_9.addWidget(self.checkBox_phe_lettuce)
        self.comboBox = QtWidgets.QComboBox(self.groupBox_4)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.horizontalLayout_9.addWidget(self.comboBox)
        self.line_4 = QtWidgets.QFrame(self.groupBox_4)
        self.line_4.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.horizontalLayout_9.addWidget(self.line_4)
        self.checkBox_phe_leaves = QtWidgets.QCheckBox(self.groupBox_4)
        self.checkBox_phe_leaves.setObjectName("checkBox_phe_leaves")
        self.horizontalLayout_9.addWidget(self.checkBox_phe_leaves)
        self.comboBox_2 = QtWidgets.QComboBox(self.groupBox_4)
        self.comboBox_2.setObjectName("comboBox_2")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.horizontalLayout_9.addWidget(self.comboBox_2)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem2)
        self.pushButton_phe_run = QtWidgets.QPushButton(self.groupBox_4)
        self.pushButton_phe_run.setObjectName("pushButton_phe_run")
        self.horizontalLayout_9.addWidget(self.pushButton_phe_run)
        self.gridLayout_3.addLayout(self.horizontalLayout_9, 0, 0, 1, 1)
        self.verticalLayout_2.addWidget(self.groupBox_4)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.groupBox_5 = QtWidgets.QGroupBox(self.page_1)
        self.groupBox_5.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.groupBox_5.setObjectName("groupBox_5")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout(self.groupBox_5)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.label_8 = QtWidgets.QLabel(self.groupBox_5)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_10.addWidget(self.label_8)
        self.lineEdit_other_path = QtWidgets.QLineEdit(self.groupBox_5)
        self.lineEdit_other_path.setMinimumSize(QtCore.QSize(200, 0))
        self.lineEdit_other_path.setText("")
        self.lineEdit_other_path.setObjectName("lineEdit_other_path")
        self.horizontalLayout_10.addWidget(self.lineEdit_other_path)
        self.toolButton_other_path = QtWidgets.QToolButton(self.groupBox_5)
        self.toolButton_other_path.setObjectName("toolButton_other_path")
        self.horizontalLayout_10.addWidget(self.toolButton_other_path)
        self.horizontalLayout_11.addLayout(self.horizontalLayout_10)
        self.comboBox_other = QtWidgets.QComboBox(self.groupBox_5)
        self.comboBox_other.setMinimumSize(QtCore.QSize(100, 0))
        self.comboBox_other.setProperty("placeholderText", "")
        self.comboBox_other.setObjectName("comboBox_other")
        self.comboBox_other.addItem("")
        self.comboBox_other.addItem("")
        self.horizontalLayout_11.addWidget(self.comboBox_other)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_11.addItem(spacerItem3)
        self.pushButton_other_run = QtWidgets.QPushButton(self.groupBox_5)
        self.pushButton_other_run.setObjectName("pushButton_other_run")
        self.horizontalLayout_11.addWidget(self.pushButton_other_run)
        self.horizontalLayout_4.addWidget(self.groupBox_5)
        self.groupBox_2 = QtWidgets.QGroupBox(self.page_1)
        self.groupBox_2.setObjectName("groupBox_2")
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout(self.groupBox_2)
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.label_9 = QtWidgets.QLabel(self.groupBox_2)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_13.addWidget(self.label_9)
        self.lineEdit_visual_path = QtWidgets.QLineEdit(self.groupBox_2)
        self.lineEdit_visual_path.setMinimumSize(QtCore.QSize(200, 0))
        self.lineEdit_visual_path.setText("")
        self.lineEdit_visual_path.setObjectName("lineEdit_visual_path")
        self.horizontalLayout_13.addWidget(self.lineEdit_visual_path)
        self.toolButton_visual_path = QtWidgets.QToolButton(self.groupBox_2)
        self.toolButton_visual_path.setObjectName("toolButton_visual_path")
        self.horizontalLayout_13.addWidget(self.toolButton_visual_path)
        self.horizontalLayout_14.addLayout(self.horizontalLayout_13)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_14.addItem(spacerItem4)
        self.pushButton_visual_model = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButton_visual_model.setObjectName("pushButton_visual_model")
        self.horizontalLayout_14.addWidget(self.pushButton_visual_model)
        self.pushButton_visual_table = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButton_visual_table.setObjectName("pushButton_visual_table")
        self.horizontalLayout_14.addWidget(self.pushButton_visual_table)
        self.horizontalLayout_4.addWidget(self.groupBox_2)
        self.verticalLayout_2.addLayout(self.horizontalLayout_4)
        spacerItem5 = QtWidgets.QSpacerItem(20, 3, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem5)
        self.toolBox.addItem(self.page_1, "")
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setGeometry(QtCore.QRect(0, 0, 1347, 311))
        self.page_2.setObjectName("page_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.page_2)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.textEdit_log = QtWidgets.QTextEdit(self.page_2)
        self.textEdit_log.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.textEdit_log.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.textEdit_log.setLineWrapMode(QtWidgets.QTextEdit.NoWrap)
        self.textEdit_log.setReadOnly(True)
        self.textEdit_log.setObjectName("textEdit_log")
        self.verticalLayout_3.addWidget(self.textEdit_log)
        self.toolBox.addItem(self.page_2, "")
        self.verticalLayout.addWidget(self.toolBox)
        self.line_12 = QtWidgets.QFrame(self.centralwidget)
        self.line_12.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_12.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_12.setObjectName("line_12")
        self.verticalLayout.addWidget(self.line_12)
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.progressBar = QtWidgets.QProgressBar(self.centralwidget)
        self.progressBar.setMinimum(0)
        self.progressBar.setProperty("value", 0)
        self.progressBar.setObjectName("progressBar")
        self.horizontalLayout_12.addWidget(self.progressBar)
        self.label_progressBar = QtWidgets.QLabel(self.centralwidget)
        self.label_progressBar.setAlignment(QtCore.Qt.AlignCenter)
        self.label_progressBar.setObjectName("label_progressBar")
        self.horizontalLayout_12.addWidget(self.label_progressBar)
        self.verticalLayout.addLayout(self.horizontalLayout_12)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1369, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)

        self.retranslateUi(MainWindow)
        self.toolBox.setCurrentIndex(0)
        self.toolBox.layout().setSpacing(6)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "In Path:"))
        self.toolButton_main_in_path.setText(_translate("MainWindow", "..."))
        self.label_3.setText(_translate("MainWindow", "Out Path:"))
        self.toolButton_main_out_path.setText(_translate("MainWindow", "..."))
        self.groupBox.setTitle(_translate("MainWindow", "Preprocessing"))
        self.checkBox_pre_allToCai.setText(_translate("MainWindow", "Single Pot"))
        self.checkBox_pre_noise.setText(_translate("MainWindow", "Denoise"))
        self.checkBox_pre_downSample.setText(_translate("MainWindow", "Downsampling"))
        self.pushButton_pre_run.setText(_translate("MainWindow", "Run"))
        self.groupBox_3.setTitle(_translate("MainWindow", "Segmentation"))
        self.checkBox_seg_lettuce.setText(_translate("MainWindow", "Plant"))
        self.checkBox_seg_singleLeaf.setText(_translate("MainWindow", "Leaf"))
        self.pushButton_seg_run.setText(_translate("MainWindow", "Run"))
        self.groupBox_4.setTitle(_translate("MainWindow", "Phenotype"))
        self.checkBox_phe_lettuce.setText(_translate("MainWindow", "Plant Type"))
        self.comboBox.setItemText(0, _translate("MainWindow", "All"))
        self.comboBox.setItemText(1, _translate("MainWindow", "株高"))
        self.comboBox.setItemText(2, _translate("MainWindow", "冠幅"))
        self.comboBox.setItemText(3, _translate("MainWindow", "紧凑度"))
        self.comboBox.setItemText(4, _translate("MainWindow", "投影面积"))
        self.comboBox.setItemText(5, _translate("MainWindow", "凸包体积"))
        self.comboBox.setItemText(6, _translate("MainWindow", "凹包体积"))
        self.comboBox.setItemText(7, _translate("MainWindow", "体素体积"))
        self.comboBox.setItemText(8, _translate("MainWindow", "叶片数"))
        self.checkBox_phe_leaves.setText(_translate("MainWindow", "Leaf Type"))
        self.comboBox_2.setItemText(0, _translate("MainWindow", "All"))
        self.comboBox_2.setItemText(1, _translate("MainWindow", "叶长"))
        self.comboBox_2.setItemText(2, _translate("MainWindow", "叶宽"))
        self.comboBox_2.setItemText(3, _translate("MainWindow", "叶面积"))
        self.comboBox_2.setItemText(4, _translate("MainWindow", "叶倾角"))
        self.comboBox_2.setItemText(5, _translate("MainWindow", "叶方位角"))
        self.comboBox_2.setItemText(6, _translate("MainWindow", "叶缘周长"))
        self.comboBox_2.setItemText(7, _translate("MainWindow", "叶缘起伏度"))
        self.comboBox_2.setItemText(8, _translate("MainWindow", "叶缘切口数"))
        self.pushButton_phe_run.setText(_translate("MainWindow", "Run"))
        self.groupBox_5.setTitle(_translate("MainWindow", "Other"))
        self.label_8.setText(_translate("MainWindow", "In Path:"))
        self.toolButton_other_path.setText(_translate("MainWindow", "..."))
        self.comboBox_other.setItemText(0, _translate("MainWindow", "Density"))
        self.comboBox_other.setItemText(1, _translate("MainWindow", "计算点数"))
        self.pushButton_other_run.setText(_translate("MainWindow", "Run"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Visualization"))
        self.label_9.setText(_translate("MainWindow", "File In Path:"))
        self.toolButton_visual_path.setText(_translate("MainWindow", "..."))
        self.pushButton_visual_model.setText(_translate("MainWindow", "3D Model"))
        self.pushButton_visual_table.setText(_translate("MainWindow", "CSV Table"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page_1), _translate("MainWindow", "【Function Area】"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page_2), _translate("MainWindow", "【Running Out】"))
        self.label_progressBar.setText(_translate("MainWindow", " --:--:-- "))

